### ISSUE TITLE
Story map is empty

### ISSUE THREAD

**Issue by thomniel** [RallyTechServices/story-map-app#21]
I have followed the instructions and the app loads an empty app.

**Comment by jmartin-rally** [comment]
Are you using the App.html code or the Ugly.html code?  

Can you open your browser's javascript console and tell us if there's anything being reported there?

**Comment by thomniel** [comment]
I have tried both the App.html and Ugly.html code, but I just tried to install the app in our production workspace and the UI Load correctly here, meaning I can select a release and PI items. Is there certain requirements to the workspace for the app to work. e.g. levels of PI items?
